disabled_rules:
  - file_length # we should discuss if we want to enable this
  - line_length # we should discuss if we want to enable this
  - function_body_length # we should discuss if we want to enable this
  - type_body_length # we should discuss if we want to enable this
  - type_name # we should discuss if we want to enable this
  - identifier_name # we should discuss if we want to enable this
  - function_parameter_count # we should discuss if we want to enable this
  - cyclomatic_complexity # we should enable this, but needs refactoring
  - todo # we should discuss if we want to enable this
  - nesting # we should discuss if we want to enable this
opt_in_rules:
  - explicit_init
  - first_where
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
trailing_whitespace:
  ignores_empty_lines: true
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods